config/routes.rb
Rails.application.routes.draw do



  resources :energies
  resources :internets
  resources :records
  resources :businesses
  resources :organizes
  resources :communities
  resources :schedules
  resources :teach_classes
  resources :courses
  resources :class2s
  resources :departments
  resources :class1s
  resources :ads
  resources :admins
  resources :teachers
  resources :students
  resources :clients
  resources :lists
  devise_for :users


  get '/teach_classes/read/:id', to: 'teach_classes#read'
  get '/schedules/read/:id', to: 'schedules#read'
  #查看社团
  get '/organizes/read/:id', to: 'organizes#read',as:"organize_read"
  get '/schedules/selection/:id', to: 'schedules#selection' ,as:"selection"
  #选课
  get '/schedules/add_course/:id,:tid', to: 'schedules#add_course' ,as:"add_course"
  #加入社团
  get '/organizes/add_organzie/:id,:cid', to: 'organizes#add_organize' ,as:"add_organize"
  #管理社团
  get '/organizes/my_organzie/:id', to: 'organizes#my_organize' ,as:"my_organize"
  #解散社团
  get '/communities/delete_community/:id', to: 'communities#delete_community' ,as:"delete_community"
 #查找社团
  post '/communities/search',to: 'communities#search'
  #下载文件
  get '/businesses/file_download/:id',to:'businesses#file_download',as:"file_download"
  #我的创业项目
  get '/businesses/mybusiness/:id',to:'businesses#mybusiness',as:"mybusiness"
  #我带领的创业项目
  get '/teachers/mentor/:id',to:'teachers#mentor',as:"mentor"
  #我的教学班级
  get '/teach_classes/myclass/:id', to: 'teach_classes#myclass',as: 'my_class'
  #查找创业项目
  post '/businesses/search',to: 'businesses#search'
  #更改状态
  post '/businesses/edit_state/:id',to:'businesses#edit_state'
 #查找课程
  post '/schedules/search/:id',to: 'schedules#search'
  #查找班级
  post '/class1s/search',to: 'class1s#search'
  #查看班级
  get '/departments/read/:id', to: 'departments#read',as:"read_department"
  #主页
  root to: "home#index"
  #登录账户
  get 'accounts/new'
  post 'accounts/create'
  get '/accounts/index/:id',to:"accounts#index" ,as:"account"
  #充值
  get '/accounts/charge/:id',to:"accounts#charge",as:"accounts_charge"
  post '/accounts/charge/:id',to:"accounts#charge"
  #交易记录
  get '/records/read/:id', to: 'records#read',as:"read_records"
  #电费
  get '/energies/read/:id', to: 'energies#read',as:"read_energy"
  get '/energies/charge/:id',to:"energies#charge"
  post '/energies/charge/:id',to:"energies#charge"
  #网费
  get '/internets/read/:id', to: 'internets#read',as:"read_internet"
  get '/internets/charge/:id',to:"internets#charge"
  post '/internets/charge/:id',to:"internets#charge"
  #验证密码
  get 'sessions/new'
  post 'sessions/create_internet'
  post 'sessions/create_energy'
  post 'sessions/create'


end

app/models/account.rb
  class Account < ActiveRecord::Base
    has_secure_password
    validates :account_id  ,uniqueness: true

    end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/business.rb
class Business < ApplicationRecord
   validates_uniqueness_of  :business_id,:scope=>:leader_id
end

app/models/class1.rb
class Class1 < ApplicationRecord

  has_many :students
  has_one :teacher

end

app/models/class2.rb
class Class2 < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
  validates_uniqueness_of  :community_id
end

app/models/course.rb
class Course < ApplicationRecord
  validates :course_id  ,uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/energy.rb
class Energy < ApplicationRecord
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/organize.rb
class Organize < ApplicationRecord
  validates_uniqueness_of  :community_id,:scope=>:student_id
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  validates_uniqueness_of  :teachclass_id,:scope=>:student_id
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :class1, optional: true
  validates :student_id ,presence:true ,uniqueness: true
  validates :name ,presence: true
  validates :class_id,presence: true
  validates :dormitory ,presence: true

  validates :phone , presence: true ,length: {is: 11}
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :class1,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :user_id, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  devise :database_authenticatable, :authentication_keys => [:user_id]

  #has_one :student

  def admin?
    self.role == "admin"
  end

  def student?
    self.role == "student"
  end
  def teacher?
    self.role == "teacher"
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.user_id || self.email
  end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      where(conditions.to_h).where(["lower(user_id) = :value OR lower(email) = :value", { :value => login.downcase }]).first

    elsif conditions.has_key?(:user_id) || conditions.has_key?(:email)

      where(conditions.to_h).first

    end

  end



end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  def search

    @businesses= Business.where('business_id like :str', str: "%#{params[:id]}%")
    render "businesses/index"
  end


  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  def file_download

    @business = Business.find(params[:id])
    send_file "#{Rails.root}/public/upload/#{@business.plan_url}"
  end

  def mybusiness
    @user = User.find(params[:id])
    @student =Student.find_by_student_id(@user.user_id)
    @businesses = Business.where(leader_id: @student.student_id)

    render 'businesses/index'
  end

  def edit_state
     @business =Business.find(params[:id])
     state = params[:state]
    @business.state = state
    @business.update(business_params)

    render "teachers/mentor"
  end

  def create

    @business = Business.new(business_params)
    uploaded_file = params[:business][:plan_url]
    File.open(Rails.root.join('public', 'upload', uploaded_file.original_filename), 'wb') do |file|
      file.write(uploaded_file.read)
    end
    @business.plan_url = uploaded_file.original_filename
    @business.state = "待审核"
    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
          params.require(:business).permit(:business_id, :leader_id, :leader_name,:plan_url , :mentor, :state)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <p>项目名称</p>
    <%= form.text_field :business_id %>
  </div>

  <div class="field">
    <p>学号</p>
    <%= form.text_field :leader_id %>
  </div>

  <div class="field">
    <p>姓名</p>
    <%= form.text_field :leader_name %>
  </div>

  <div class="field">
    <p>上传计划书</p>
    <%= form.file_field :plan_url %>
  </div>

  <div class="field">
    <p>导师</p>
    <%= form.text_field :mentor %>
  </div>

  <div class="field">
    <% form.text_field :state=>"待审核" %>
  </div>
 <br>
  <div class="actions">
    <%= form.submit "确定" %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>修改项目</h1>

<%= render 'form', business: @business %>

<%= link_to '详情', @business %> |
<%= link_to '返回', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>创新与创业项目</h1>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">创业项目查找</a>
  <%= form_tag controller: "businesses", action: "search", method: "post" do %>
    <%= label_tag(:id, "搜索:") %>
    <%= text_field_tag :id %>
    <%= submit_tag("确定") %>
  <% end %>
</nav>
<table  class="table table-hover">
  <thead>
    <tr>
      <th>项目名称</th>
      <th>学号</th>
      <th>姓名</th>
      <th>计划书</th>
      <th>导师</th>
      <th>状态</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.business_id %></td>
        <td><%= business.leader_id %></td>
        <td><%= business.leader_name %></td>
        <td><%= link_to business.plan_url,file_download_path(business) %></td>
        <td><%= business.mentor %></td>
        <td><%= business.state %></td>
        <td><%= link_to '删除', business, method: :delete, data: { confirm: '确认删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增创业项目', new_business_path %>
<%= link_to '返回',root_path %>

app/views/businesses/new.html.erb
<h1>申请创业项目</h1>

<%= render 'form', business: @business %>

<%= link_to '返回', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>项目名:</strong>
  <%= @business.business_id %>
</p>

<p>
  <strong>创建者:</strong>
  <%= @business.leader_name %>
</p>

<p>
  <strong>计划书:</strong>
  <%= @business.plan_url %>
</p>

<p>
  <strong>导师:</strong>
  <%= @business.mentor %>
</p>

<p>
  <strong>状态:</strong>
  <%= @business.state %>
</p>

<%= link_to '修改', edit_business_path(@business) %> |
<%= link_to '返回', root_path %>