config/routes.rb
Rails.application.routes.draw do



  resources :energies
  resources :internets
  resources :records
  resources :businesses
  resources :organizes
  resources :communities
  resources :schedules
  resources :teach_classes
  resources :courses
  resources :class2s
  resources :departments
  resources :class1s
  resources :ads
  resources :admins
  resources :teachers
  resources :students
  resources :clients
  resources :lists
  devise_for :users


  get '/teach_classes/read/:id', to: 'teach_classes#read'
  get '/schedules/read/:id', to: 'schedules#read'
  #查看社团
  get '/organizes/read/:id', to: 'organizes#read',as:"organize_read"
  get '/schedules/selection/:id', to: 'schedules#selection' ,as:"selection"
  #选课
  get '/schedules/add_course/:id,:tid', to: 'schedules#add_course' ,as:"add_course"
  #加入社团
  get '/organizes/add_organzie/:id,:cid', to: 'organizes#add_organize' ,as:"add_organize"
  #管理社团
  get '/organizes/my_organzie/:id', to: 'organizes#my_organize' ,as:"my_organize"
  #解散社团
  get '/communities/delete_community/:id', to: 'communities#delete_community' ,as:"delete_community"
 #查找社团
  post '/communities/search',to: 'communities#search'
  #下载文件
  get '/businesses/file_download/:id',to:'businesses#file_download',as:"file_download"
  #我的创业项目
  get '/businesses/mybusiness/:id',to:'businesses#mybusiness',as:"mybusiness"
  #我带领的创业项目
  get '/teachers/mentor/:id',to:'teachers#mentor',as:"mentor"
  #我的教学班级
  get '/teach_classes/myclass/:id', to: 'teach_classes#myclass',as: 'my_class'
  #查找创业项目
  post '/businesses/search',to: 'businesses#search'
  #更改状态
  post '/businesses/edit_state/:id',to:'businesses#edit_state'
 #查找课程
  post '/schedules/search/:id',to: 'schedules#search'
  #查找班级
  post '/class1s/search',to: 'class1s#search'
  #查看班级
  get '/departments/read/:id', to: 'departments#read',as:"read_department"
  #主页
  root to: "home#index"
  #登录账户
  get 'accounts/new'
  post 'accounts/create'
  get '/accounts/index/:id',to:"accounts#index" ,as:"account"
  #充值
  get '/accounts/charge/:id',to:"accounts#charge",as:"accounts_charge"
  post '/accounts/charge/:id',to:"accounts#charge"
  #交易记录
  get '/records/read/:id', to: 'records#read',as:"read_records"
  #电费
  get '/energies/read/:id', to: 'energies#read',as:"read_energy"
  get '/energies/charge/:id',to:"energies#charge"
  post '/energies/charge/:id',to:"energies#charge"
  #网费
  get '/internets/read/:id', to: 'internets#read',as:"read_internet"
  get '/internets/charge/:id',to:"internets#charge"
  post '/internets/charge/:id',to:"internets#charge"
  #验证密码
  get 'sessions/new'
  post 'sessions/create_internet'
  post 'sessions/create_energy'
  post 'sessions/create'


end

app/models/account.rb
  class Account < ActiveRecord::Base
    has_secure_password
    validates :account_id  ,uniqueness: true

    end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/business.rb
class Business < ApplicationRecord
   validates_uniqueness_of  :business_id,:scope=>:leader_id
end

app/models/class1.rb
class Class1 < ApplicationRecord

  has_many :students
  has_one :teacher

end

app/models/class2.rb
class Class2 < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
  validates_uniqueness_of  :community_id
end

app/models/course.rb
class Course < ApplicationRecord
  validates :course_id  ,uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/energy.rb
class Energy < ApplicationRecord
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/organize.rb
class Organize < ApplicationRecord
  validates_uniqueness_of  :community_id,:scope=>:student_id
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  validates_uniqueness_of  :teachclass_id,:scope=>:student_id
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :class1, optional: true
  validates :student_id ,presence:true ,uniqueness: true
  validates :name ,presence: true
  validates :class_id,presence: true
  validates :dormitory ,presence: true

  validates :phone , presence: true ,length: {is: 11}
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :class1,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :user_id, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  devise :database_authenticatable, :authentication_keys => [:user_id]

  #has_one :student

  def admin?
    self.role == "admin"
  end

  def student?
    self.role == "student"
  end
  def teacher?
    self.role == "teacher"
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.user_id || self.email
  end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      where(conditions.to_h).where(["lower(user_id) = :value OR lower(email) = :value", { :value => login.downcase }]).first

    elsif conditions.has_key?(:user_id) || conditions.has_key?(:email)

      where(conditions.to_h).first

    end

  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def show

  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user.admin? %>
  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: cornflowerblue;">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <%= link_to "教师管理", teachers_path ,:class=>"nav-link"%>
        </li>
        <li class="nav-item active">
          <%=link_to "学生管理",students_path ,:class => "nav-link"%>
        </li>
        <li class="nav-item active">

          <%= link_to"班级管理", class1s_path,:class => "nav-link" %>
        </li>
        <li class="nav-item active">
          <%=link_to "院系管理",departments_path,:class => "nav-link" %>
        </li>
        <li class="nav-item active">

          <%=link_to "课程管理",courses_path ,:class => "nav-link"%>
        </li>
        <li class="nav-item active">
          <%=link_to "教学管理",teach_classes_path,:class => "nav-link" %>
        </li>
        <li class="nav-item active">
          <%=link_to "创业计划管理",businesses_path,:class => "nav-link" %>
        </li>
        <li class="nav-item active">
          <%=link_to "账户信息",ad_path(current_user),:class => "nav-link" %>
        </li>
      </ul>
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('注册', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>
  </nav>





<% elsif current_user.student? %>
  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: cornflowerblue;">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "个人信息", client_path(current_user),:class => "nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to "选课",{controller: "schedules",action: "read",id:(current_user)},:class => "nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to "我的社团",{controller: "organizes",action: "read",id:(current_user)},:class => "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "创新与创业",mybusiness_path(current_user),:class => "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "我的账户",{controller: "accounts",action: "index",id:(current_user)},:class => "nav-link" %>
        </li>
      </ul>
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('注册', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>
  </nav>






<% elsif current_user.teacher? %>
  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: cornflowerblue;">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%=link_to "个人信息",list_path(current_user),:class => "nav-link" %>
        </li>
        <li class="nav-item active">
          <%=link_to "我管理的班级", class2_path(current_user),:class => "nav-link" %>
        </li>
        <li class="nav-item active">
          <%=link_to "我教授的课程",{controller: "teach_classes",action: "read",id:(current_user)},:class => "nav-link" %>
        </li>

        <li class="nav-item active">
          <%=link_to "我带领的创业项目",mentor_path(current_user),:class => "nav-link" %>
        </li>
      </ul>
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('注册', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>
  </nav>




<% else %>
  <% root_path %>
<% end %>