config/routes.rb
Rails.application.routes.draw do



  resources :energies
  resources :internets
  resources :records
  resources :businesses
  resources :organizes
  resources :communities
  resources :schedules
  resources :teach_classes
  resources :courses
  resources :class2s
  resources :departments
  resources :class1s
  resources :ads
  resources :admins
  resources :teachers
  resources :students
  resources :clients
  resources :lists
  devise_for :users


  get '/teach_classes/read/:id', to: 'teach_classes#read'
  get '/schedules/read/:id', to: 'schedules#read'
  #查看社团
  get '/organizes/read/:id', to: 'organizes#read',as:"organize_read"
  get '/schedules/selection/:id', to: 'schedules#selection' ,as:"selection"
  #选课
  get '/schedules/add_course/:id,:tid', to: 'schedules#add_course' ,as:"add_course"
  #加入社团
  get '/organizes/add_organzie/:id,:cid', to: 'organizes#add_organize' ,as:"add_organize"
  #管理社团
  get '/organizes/my_organzie/:id', to: 'organizes#my_organize' ,as:"my_organize"
  #解散社团
  get '/communities/delete_community/:id', to: 'communities#delete_community' ,as:"delete_community"
 #查找社团
  post '/communities/search',to: 'communities#search'
  #下载文件
  get '/businesses/file_download/:id',to:'businesses#file_download',as:"file_download"
  #我的创业项目
  get '/businesses/mybusiness/:id',to:'businesses#mybusiness',as:"mybusiness"
  #我带领的创业项目
  get '/teachers/mentor/:id',to:'teachers#mentor',as:"mentor"
  #我的教学班级
  get '/teach_classes/myclass/:id', to: 'teach_classes#myclass',as: 'my_class'
  #查找创业项目
  post '/businesses/search',to: 'businesses#search'
  #更改状态
  post '/businesses/edit_state/:id',to:'businesses#edit_state'
 #查找课程
  post '/schedules/search/:id',to: 'schedules#search'
  #查找班级
  post '/class1s/search',to: 'class1s#search'
  #查看班级
  get '/departments/read/:id', to: 'departments#read',as:"read_department"
  #主页
  root to: "home#index"
  #登录账户
  get 'accounts/new'
  post 'accounts/create'
  get '/accounts/index/:id',to:"accounts#index" ,as:"account"
  #充值
  get '/accounts/charge/:id',to:"accounts#charge",as:"accounts_charge"
  post '/accounts/charge/:id',to:"accounts#charge"
  #交易记录
  get '/records/read/:id', to: 'records#read',as:"read_records"
  #电费
  get '/energies/read/:id', to: 'energies#read',as:"read_energy"
  get '/energies/charge/:id',to:"energies#charge"
  post '/energies/charge/:id',to:"energies#charge"
  #网费
  get '/internets/read/:id', to: 'internets#read',as:"read_internet"
  get '/internets/charge/:id',to:"internets#charge"
  post '/internets/charge/:id',to:"internets#charge"
  #验证密码
  get 'sessions/new'
  post 'sessions/create_internet'
  post 'sessions/create_energy'
  post 'sessions/create'


end

app/models/account.rb
  class Account < ActiveRecord::Base
    has_secure_password
    validates :account_id  ,uniqueness: true

    end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/business.rb
class Business < ApplicationRecord
   validates_uniqueness_of  :business_id,:scope=>:leader_id
end

app/models/class1.rb
class Class1 < ApplicationRecord

  has_many :students
  has_one :teacher

end

app/models/class2.rb
class Class2 < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
  validates_uniqueness_of  :community_id
end

app/models/course.rb
class Course < ApplicationRecord
  validates :course_id  ,uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/energy.rb
class Energy < ApplicationRecord
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/organize.rb
class Organize < ApplicationRecord
  validates_uniqueness_of  :community_id,:scope=>:student_id
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  validates_uniqueness_of  :teachclass_id,:scope=>:student_id
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :class1, optional: true
  validates :student_id ,presence:true ,uniqueness: true
  validates :name ,presence: true
  validates :class_id,presence: true
  validates :dormitory ,presence: true

  validates :phone , presence: true ,length: {is: 11}
end

app/models/teach_class.rb
class TeachClass < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :class1,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :user_id, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  devise :database_authenticatable, :authentication_keys => [:user_id]

  #has_one :student

  def admin?
    self.role == "admin"
  end

  def student?
    self.role == "student"
  end
  def teacher?
    self.role == "teacher"
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.user_id || self.email
  end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      where(conditions.to_h).where(["lower(user_id) = :value OR lower(email) = :value", { :value => login.downcase }]).first

    elsif conditions.has_key?(:user_id) || conditions.has_key?(:email)

      where(conditions.to_h).first

    end

  end



end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  def mentor
    @user =User.find(params[:id])
    @teacher = Teacher.find_by_teacher_id(@user.user_id)
    @businesses = Business.where(mentor: @teacher.teacher_id)

    render "teachers/mentor"
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:teacher_id, :name, :role, :sex, :adress, :phone)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>教师工号</p>
    <%= form.text_field :teacher_id %>
  </div>

  <div class="field">
   <p>姓名</p>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <p>权限</p>
    <%= form.select :role,['teacher']%>

  </div>


  <div class="field">
    <p>性别</p>
    <%= form.select :sex, [['男', '男'], ['女', '女']]%>
 </div>

  <div class="field">
    <p>地址</p>
    <%= form.text_field :adress %>
  </div>

  <div class="field">
    <p>联系电话</p>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', root_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>教师管理</h1>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>教师号</th>
      <th>姓名</th>
      <th>性别</th>
      <th>办公地点</th>
      <th>联系电话</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.teacher_id %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.sex %></td>
        <td><%= teacher.adress %></td>
        <td><%= teacher.phone %></td>
        <td><%= link_to '详情', teacher %></td>
        <td><%= link_to '修改', edit_teacher_path(teacher) %></td>
        <td><%= link_to '删除', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增老师', new_teacher_path %>
<%=link_to"返回",root_path %>

app/views/teachers/mentor.html.erb
<p id="notice"><%= notice %></p>

<h1>创新与创业项目</h1>

<table>
  <thead>
  <tr>
    <th>项目名称</th>
    <th>学号</th>
    <th>姓名</th>
    <th>计划书</th>
    <th>导师</th>
    <th>状态</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @businesses.each do |business| %>
    <tr>
      <td><%= business.business_id %></td>
      <td><%= business.leader_id %></td>
      <td><%= business.leader_name %></td>
      <td><%= link_to business.plan_url,file_download_path(business) %></td>
      <td><%= business.mentor %></td>
      <td><%= business.state %></td>
      <td>
      <%= form_with(model: business, local: true) do |form| %>
         <%= form.select :state,[['待审核','待审核'],['审核中','审核中'],['审核通过','审核通过']] %>
         <%= form.submit "确定" %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to '返回',root_path %>

app/views/teachers/new.html.erb
<h1>新建教师</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', root_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>教师ID:</strong>
  <%= @teacher.teacher_id %>
</p>

<p>
  <strong>姓名:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>性别:</strong>
  <%= @teacher.sex %>
</p>

<p>
  <strong>办公地点:</strong>
  <%= @teacher.adress %>
</p>

<p>
  <strong>电话:</strong>
  <%= @teacher.phone %>
</p>

<%= link_to '修改', edit_teacher_path(@teacher) %> |
<%= link_to '返回', root_path %>