config/routes.rb
Rails.application.routes.draw do



  resources :energies
  resources :internets
  resources :records
  resources :businesses
  resources :organizes
  resources :communities
  resources :schedules
  resources :teach_classes
  resources :courses
  resources :class2s
  resources :departments
  resources :class1s
  resources :ads
  resources :admins
  resources :teachers
  resources :students
  resources :clients
  resources :lists
  devise_for :users


  get '/teach_classes/read/:id', to: 'teach_classes#read'
  get '/schedules/read/:id', to: 'schedules#read'
  #查看社团
  get '/organizes/read/:id', to: 'organizes#read',as:"organize_read"
  get '/schedules/selection/:id', to: 'schedules#selection' ,as:"selection"
  #选课
  get '/schedules/add_course/:id,:tid', to: 'schedules#add_course' ,as:"add_course"
  #加入社团
  get '/organizes/add_organzie/:id,:cid', to: 'organizes#add_organize' ,as:"add_organize"
  #管理社团
  get '/organizes/my_organzie/:id', to: 'organizes#my_organize' ,as:"my_organize"
  #解散社团
  get '/communities/delete_community/:id', to: 'communities#delete_community' ,as:"delete_community"
 #查找社团
  post '/communities/search',to: 'communities#search'
  #下载文件
  get '/businesses/file_download/:id',to:'businesses#file_download',as:"file_download"
  #我的创业项目
  get '/businesses/mybusiness/:id',to:'businesses#mybusiness',as:"mybusiness"
  #我带领的创业项目
  get '/teachers/mentor/:id',to:'teachers#mentor',as:"mentor"
  #我的教学班级
  get '/teach_classes/myclass/:id', to: 'teach_classes#myclass',as: 'my_class'
  #查找创业项目
  post '/businesses/search',to: 'businesses#search'
  #更改状态
  post '/businesses/edit_state/:id',to:'businesses#edit_state'
 #查找课程
  post '/schedules/search/:id',to: 'schedules#search'
  #查找班级
  post '/class1s/search',to: 'class1s#search'
  #查看班级
  get '/departments/read/:id', to: 'departments#read',as:"read_department"
  #主页
  root to: "home#index"
  #登录账户
  get 'accounts/new'
  post 'accounts/create'
  get '/accounts/index/:id',to:"accounts#index" ,as:"account"
  #充值
  get '/accounts/charge/:id',to:"accounts#charge",as:"accounts_charge"
  post '/accounts/charge/:id',to:"accounts#charge"
  #交易记录
  get '/records/read/:id', to: 'records#read',as:"read_records"
  #电费
  get '/energies/read/:id', to: 'energies#read',as:"read_energy"
  get '/energies/charge/:id',to:"energies#charge"
  post '/energies/charge/:id',to:"energies#charge"
  #网费
  get '/internets/read/:id', to: 'internets#read',as:"read_internet"
  get '/internets/charge/:id',to:"internets#charge"
  post '/internets/charge/:id',to:"internets#charge"
  #验证密码
  get 'sessions/new'
  post 'sessions/create_internet'
  post 'sessions/create_energy'
  post 'sessions/create'


end

app/models/account.rb
  class Account < ActiveRecord::Base
    has_secure_password
    validates :account_id  ,uniqueness: true

    end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/business.rb
class Business < ApplicationRecord
   validates_uniqueness_of  :business_id,:scope=>:leader_id
end

app/models/class1.rb
class Class1 < ApplicationRecord

  has_many :students
  has_one :teacher

end

app/models/class2.rb
class Class2 < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
  validates_uniqueness_of  :community_id
end

app/models/course.rb
class Course < ApplicationRecord
  validates :course_id  ,uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/energy.rb
class Energy < ApplicationRecord
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/organize.rb
class Organize < ApplicationRecord
  validates_uniqueness_of  :community_id,:scope=>:student_id
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  validates_uniqueness_of  :teachclass_id,:scope=>:student_id
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :class1, optional: true
  validates :student_id ,presence:true ,uniqueness: true
  validates :name ,presence: true
  validates :class_id,presence: true
  validates :dormitory ,presence: true

  validates :phone , presence: true ,length: {is: 11}
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :class1,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :user_id, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  devise :database_authenticatable, :authentication_keys => [:user_id]

  #has_one :student

  def admin?
    self.role == "admin"
  end

  def student?
    self.role == "student"
  end
  def teacher?
    self.role == "teacher"
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.user_id || self.email
  end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      where(conditions.to_h).where(["lower(user_id) = :value OR lower(email) = :value", { :value => login.downcase }]).first

    elsif conditions.has_key?(:user_id) || conditions.has_key?(:email)

      where(conditions.to_h).first

    end

  end



end

app/controllers/teach_classes_controller.rb
class TeachClassesController < ApplicationController
  before_action :set_teach_class, only: [:show, :edit, :update, :destroy]

  # GET /teach_classes
  # GET /teach_classes.json
  def index
    @teach_classes = TeachClass.all
  end

  def read
    @user = User.find(params[:id])
    @teacher = Teacher.find_by_teacher_id(@user.user_id)
    @teach_classes= TeachClass.where(teacher_id: @teacher.teacher_id)

    render "teach_classes/index"

  end

  def myclass
    @teacher_class = TeachClass.find(params[:id])
    @teacher = Teacher.find_by_teacher_id(@teacher_class.teacher_id)
    @schedules = Schedule.where(teachclass_id:@teacher_class.course_id)

    @schedules.each do |s|
      @students= Student.where(student_id: s.student_id)

    end

    render "teach_classes/myclass"
  end
  def show
  end

  # GET /teach_classes/new
  def new
    @teach_class = TeachClass.new
  end

  # GET /teach_classes/1/edit
  def edit
  end

  # POST /teach_classes
  # POST /teach_classes.json
  def create
    @teach_class = TeachClass.new(teach_class_params)
    @course = Course.new(course_id: @teach_class.course_id,describe: @teach_class.name)
    @course.save
    respond_to do |format|
      if @teach_class.save
        format.html { redirect_to @teach_class, notice: 'Teach class was successfully created.' }
        format.json { render :show, status: :created, location: @teach_class }
      else
        format.html { render :new }
        format.json { render json: @teach_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teach_classes/1
  # PATCH/PUT /teach_classes/1.json
  def update
    respond_to do |format|
      if @teach_class.update(teach_class_params)
        format.html { redirect_to @teach_class, notice: 'Teach class was successfully updated.' }
        format.json { render :show, status: :ok, location: @teach_class }
      else
        format.html { render :edit }
        format.json { render json: @teach_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teach_classes/1
  # DELETE /teach_classes/1.json
  def destroy
    @teach_class.destroy
    respond_to do |format|
      format.html { redirect_to teach_classes_url, notice: 'Teach class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teach_class
      @teach_class = TeachClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teach_class_params
      params.require(:teach_class).permit(:teacher_id, :course_id, :classroom_id,:class_time,:name)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/teach_classes_helper.rb
module TeachClassesHelper
end

app/views/teach_classes/_form.html.erb
<%= form_with(model: teach_class, local: true) do |form| %>
  <% if teach_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teach_class.errors.count, "error") %> prohibited this teach_class from being saved:</h2>

      <ul>
        <% teach_class.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>教师工号</p>
    <%= form.text_field :teacher_id %>
  </div>

  <div class="field">
    <p>课程ID</p>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <p>课程名称</p>
    <%= form.text_field :name%>
  </div>

  <div class="field">
    <p>所在教室</p>
    <%= form.text_field :classroom_id %>
  </div>
  <div>
    <p>上课时间</p>
    <%=form.text_field :class_time %>
  </div>
 <br>
  <div class="actions">
    <%= form.submit "确定" %>
  </div>
<% end %>

app/views/teach_classes/edit.html.erb
<h1>Editing Teach Class</h1>

<%= render 'form', teach_class: @teach_class %>

<%= link_to 'Show', @teach_class %> |
<%= link_to 'Back', root_path %>

app/views/teach_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>教学课程</h1>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>教师ID</th>
      <th>课程ID</th>
      <th>教学教室</th>
      <th>上课时间</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teach_classes.each do |teach_class| %>
      <tr>
        <td><%= teach_class.teacher_id %></td>
        <td><%= teach_class.course_id %></td>
        <td><%= teach_class.classroom_id %></td>
        <td><%= teach_class.class_time %></td>
        <td><%= link_to '详情', my_class_path(teach_class.id) %></td>
        <td><%= link_to '修改', edit_teach_class_path(teach_class) %></td>
        <td><%= link_to '删除', teach_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建教学课程', new_teach_class_path %>
<%= link_to '返回',root_path %>

app/views/teach_classes/myclass.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>授课老师:</strong>
  <%=link_to @teacher.name,teacher_path(@teacher) %>
</p>

<table  class="table table-hover">
  <thead>
  <tr>
    <th>学号</th>
    <th>姓名</th>
    <th>班级</th>
    <th>性别</th>
    <th>电话</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.student_id %></td>
      <td><%= student.name %></td>
      <td><%=student.class_id %></td>
      <td><%= student.sex %></td>
      <td><%= student.phone %></td>
      <td><%= link_to '详情', student %></td>
      <td><%= link_to '修改', edit_student_path(student) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to '返回', root_path %>

app/views/teach_classes/new.html.erb
<h1>新增教学课程</h1>

<%= render 'form', teach_class: @teach_class %>

<%= link_to '返回', root_path %>

app/views/teach_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>教师：</strong>
  <%= @teach_class.teacher_id%>
</p>

<p>
  <strong>课程名:</strong>
  <%= @teach_class.course_id %>
</p>

<p>
  <strong>教室:</strong>
  <%= @teach_class.classroom_id %>
</p>
<p>
  <strong>上课时间:</strong>
  <%=@teach_class.class_time %>
</p>
<%= link_to 'Edit', edit_teach_class_path(@teach_class) %> |
<%= link_to 'Back', root_path %>